FROM node:18

# COPY BoozeOrNo/frontend/package.json ./package.json
# COPY BoozeOrNo/frontend/package-lock.json ./package-lock.json
COPY frontend /workspaces/Rand-A-Pizza/frontend
WORKDIR /workspaces/Rand-A-Pizza/frontend/rand-a-pizza

RUN npm install @supabase/supabase-js

RUN npm install

CMD ["npm", "run", "dev"]
