FROM python:3.11

# Copy database file into the container	
COPY db /workspaces/Rand-A-Pizza/db
# point to the workdir
WORKDIR /workspaces/Rand-A-Pizza/db

# Command to run when the container starts
CMD ["ls"]




