FROM python:3.11
# Install SQLite
# RUN apk --no-cache add sqlite
# Copy database file into the container	
COPY db /workspaces/Rand-A-Pizza/db
# point to the workdir
WORKDIR /workspaces/Rand-A-Pizza/db
# Expose the port if needed
# EXPOSE 1433
# Command to run when the container starts
CMD ["ls"]




