FROM python:3.11
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y nodejs

# paths for render
COPY backend ./backend
COPY requirements.txt .
RUN pip install -r requirements.txt
WORKDIR ./backend

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
